package com.ukg.telestaff.sdlc.agent;

import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;

/**
 * Registry of pre-canned demo responses, one per agent ID.
 *
 * <p>Responses are rich Markdown strings that mimic realistic Claude output.
 * They reference actual Telestaff class names, packages, Jira IDs, and
 * database table names so the demo feels authentic.
 *
 * <p>User inputs (Jira ID, feature description, etc.) are spliced into
 * the response text via {@link #getResponse(String, Map)} to make each
 * demo run appear personalised.
 */
@Component
public class DemoResponseRegistry {

    private static final Map<String, String> RESPONSES = new HashMap<>();

    static {

        // ── customer-issue-analyzer ──────────────────────────────────────────
        RESPONSES.put("customer-issue-analyzer", lines(
            "# 🔬 Customer Issue Analysis — PS-821311",
            "",
            "## Classification",
            "| Attribute | Value |",
            "|-----------|-------|",
            "| **Type** | Code Bug |",
            "| **Subsystem** | Contact Manager — Queue Processing |",
            "| **Severity** | High |",
            "| **Regression** | ✅ Yes — introduced in release `2024.4.2` |",
            "",
            "## Root Cause Summary",
            "A `NullPointerException` in `ContactManagerServiceImpl.processQueueEntry()` at line 847 occurs",
            "when `CallQueueTbl.getContactMethodTbl()` returns `null` for resources whose contact method",
            "was soft-deleted without cascading the update to in-flight queue entries.",
            "",
            "The guard added in PS-789034 (release 2024.4.0) removed the null check that previously",
            "existed at line 831 as part of a performance refactor — this is the regression point.",
            "",
            "## Historical Matches",
            "| Ticket | Summary | Resolution |",
            "|--------|---------|-----------|",
            "| PS-789034 | Contact method null after soft-delete | Added null guard — later removed |",
            "| PS-756120 | Queue entry stuck in JOB_TRIGGERED | Missing DONE_SENTINEL on exception path |",
            "| PS-701445 | ContactManagerJob skipping institutions | TenantContext not propagated to child thread |",
            "",
            "## Affected Code",
            "```",
            "com.kronos.telestaff.service.impl.ContactManagerServiceImpl",
            "  └─ processQueueEntry(ContactManagerCallQueueTbl, ContactConfiguration) : line 847",
            "com.kronos.telestaff.dao.ContactManagerCallQueueDao",
            "  └─ findPendingByInstitution(Long institutionId, int limit) : missing JOIN",
            "```",
            "",
            "## Investigation Checklist",
            "- [x] Confirmed NPE in production logs: `contact-manager.log` 2024-11-14 03:17 UTC",
            "- [x] Regression introduced in commit `a3f92c1` (PS-789034, branch `feature/contact-perf`)",
            "- [ ] Verify soft-deleted contact methods still have FK references in `contact_manager_call_queue_tbl`",
            "- [ ] Check if `ContactConfigurationProvider` cache is stale after contact method deletion",
            "- [ ] Confirm fix needed in `ContactManagerServiceImpl` line 847 — restore null guard",
            "- [ ] Add regression test in `ContactManagerServiceImplTest`",
            "",
            "## Recommended Fix",
            "Restore the null check before calling `.getContactMethodTbl().getContactMethodTypeEnum()`.",
            "Additionally, add a `LEFT JOIN FETCH` on `contactMethodTbl` in the DAO query to prevent",
            "`LazyInitializationException` when the queue is processed outside the original transaction.",
            "",
            "## Estimated Effort",
            "**2–3 hours** — code fix + unit test + regression test. No DB migration required."
        ));

        // ── feature-design-hld ───────────────────────────────────────────────
        RESPONSES.put("feature-design-hld", lines(
            "# 🏗️ High Level Design — Push Notification Preference Management",
            "**Jira Epic:** PS-12345 | **Complexity:** Medium | **Target Release:** 2025.1",
            "",
            "## 1. Context & Goals",
            "Allow workforce resources to configure per-channel notification preferences",
            "(push, email, SMS) at the institution level without admin intervention.",
            "",
            "**Goals:**",
            "- Self-service preference management by resources",
            "- Per-institution enable/disable via `@CheckFeatureStatusForInstitution`",
            "- Zero-downtime rollout behind LaunchDarkly flag `PS-12345-push-notification-prefs`",
            "",
            "## 2. Affected Modules",
            "| Module | Change Type |",
            "|--------|------------|",
            "| `telestaff-domain` | New entity `NotificationPreferenceTbl` |",
            "| `telestaff-services` | New `NotificationPreferenceService` + DAO |",
            "| `telestaff-web` | New REST endpoint `POST /api/v2/notification-preferences` |",
            "| `telestaff-commons` | Liquibase migration `20250101_notification_prefs.xml` |",
            "",
            "## 3. High-Level Flow",
            "```",
            "Resource → POST /api/v2/notification-preferences",
            "  → NotificationPreferenceController",
            "    → @PreAuthorize('hasRole(ROLE_RESOURCE)')",
            "    → NotificationPreferenceService.savePreference(dto)",
            "      → CommonACLService.validateResourceAccess(resourceId)",
            "      → NotificationPreferenceDao.upsert(entity)",
            "      → @NotificationPreferenceEvict (cache eviction)",
            "      → ApplicationEventService.publish(PreferenceChangedEvent)",
            "```",
            "",
            "## 4. Integration Points",
            "- **ContactManagerServiceImpl** reads preferences before dispatching notifications",
            "- **MessageGatewayService** respects opt-out flags from preferences",
            "- **InstitutionFeatureService** gates the feature per institution",
            "",
            "## 5. Non-Functional Requirements",
            "- Preference lookup: < 5 ms (Redis-cached, TTL 30 min)",
            "- Write throughput: ~200 updates/min peak",
            "- No cross-institution data visible (institution FK on entity)",
            "",
            "## 6. Open Questions",
            "1. Should preferences be copyable across institutions for the same resource?",
            "2. Default state when feature first enabled — opt-in or opt-out?",
            "3. Audit trail required? (Maps to `AuditTargetEnum` if yes)"
        ));

        // ── feature-design-lld ───────────────────────────────────────────────
        RESPONSES.put("feature-design-lld", lines(
            "# 📐 Low Level Design — Notification Preference Management",
            "**Jira Story:** PS-12345 | **Module:** telestaff-services / telestaff-web",
            "",
            "## 1. Entity: `NotificationPreferenceTbl`",
            "```java",
            "// telestaff-domain: com.kronos.telestaff.domain",
            "@Entity",
            "@Table(name = \"notification_preference_tbl\")",
            "public class NotificationPreferenceTbl extends BaseAuditTbl {",
            "",
            "    // Annotations on GETTERS per Constraint #4",
            "    private Long         notifPrefIdIn;",
            "    private ResourceTbl  resourceTbl;",
            "    private InstitutionTbl institutionTbl;  // institution-scoped",
            "    private String       channelCh;        // 'PUSH','EMAIL','SMS'",
            "    private String       enabledFl;        // 'Y'/'N'",
            "",
            "    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)",
            "    @Column(name = \"Notif_Pref_Id_In\")",
            "    public Long getNotifPrefIdIn() { return notifPrefIdIn; }",
            "}",
            "```",
            "",
            "## 2. DAO Interface",
            "```java",
            "// Extends GenericDao (kronos-common) — interface only, never concrete class",
            "public interface NotificationPreferenceDao",
            "        extends GenericDao<NotificationPreferenceTbl, Long> {",
            "",
            "    Optional<NotificationPreferenceTbl> findByResourceAndChannel(",
            "        Long resourceId, Long institutionId, String channel);",
            "",
            "    List<NotificationPreferenceTbl> findAllByResource(",
            "        Long resourceId, Long institutionId);",
            "}",
            "```",
            "",
            "## 3. Service Interface (`@PreAuthorize` here, NOT on impl)",
            "```java",
            "public interface NotificationPreferenceService {",
            "",
            "    @PreAuthorize(\"hasAnyRole('ROLE_RESOURCE', 'ROLE_SUPERVISOR')\")",
            "    NotificationPreferenceDto getPreferences(Long resourceId);",
            "",
            "    @PreAuthorize(\"hasAnyRole('ROLE_RESOURCE', 'ROLE_SUPERVISOR')\")",
            "    void savePreference(NotificationPreferenceDto dto);",
            "}",
            "```",
            "",
            "## 4. Liquibase Migration",
            "```xml",
            "<!-- telestaff-commons/changelogs/db/20250101_notification_prefs.xml -->",
            "<changeSet id=\"20250101-notification-pref-table\" author=\"harshit.jaiswal\">",
            "    <createTable tableName=\"notification_preference_tbl\">",
            "        <column name=\"Notif_Pref_Id_In\" type=\"BIGINT\" autoIncrement=\"true\">",
            "            <constraints primaryKey=\"true\"/>",
            "        </column>",
            "        <!-- Nullable first (no NOT NULL without DEFAULT) -->",
            "        <column name=\"Resource_Id_In\"     type=\"BIGINT\"/>",
            "        <column name=\"Institution_Id_In\"  type=\"BIGINT\"/>",
            "        <column name=\"Channel_Ch\"         type=\"VARCHAR(10)\"/>",
            "        <column name=\"Enabled_Fl\"         type=\"CHAR(1)\" defaultValue=\"Y\"/>",
            "    </createTable>",
            "</changeSet>",
            "```",
            "",
            "## 5. Cache Strategy",
            "- **Cache name:** `NOTIFICATION_PREFERENCE_CACHE` — tenant-aware",
            "- **TTL:** 30 min (EhCache + Redis)",
            "- **Eviction:** `@NotificationPreferenceEvict` annotation on `savePreference()`",
            "- **Key:** `{tenantId}_notif_pref_{resourceId}_{institutionId}`",
            "",
            "## 6. LaunchDarkly Flag",
            "```java",
            "// In LaunchDarklyFlagEnum (telestaff-commons):",
            "PS_12345_PUSH_NOTIFICATION_PREFS(\"PS-12345-push-notification-prefs\")",
            "```"
        ));

        // ── design-review ────────────────────────────────────────────────────
        RESPONSES.put("design-review", lines(
            "# 🔍 Design Review Report",
            "**Review Type:** Full Design Review | **Verdict:** ⚠️ Approve with Changes",
            "",
            "## Blocking Issues (must fix before implementation)",
            "",
            "### 🚫 BLOCKING-1: Missing Institution Filter on DAO Query",
            "> **File:** `NotificationPreferenceDao.findAllByResource()`",
            "> **Rule:** Multi-Tenancy Constraint — every query on institution-scoped entities",
            "> must include `WHERE institution_id = ?`. Omitting it causes cross-institution data leak.",
            "**Fix:** Add `institutionId` parameter and filter in JPQL/named query.",
            "",
            "### 🚫 BLOCKING-2: `@PreAuthorize` on ServiceImpl, not Interface",
            "> **File:** `NotificationPreferenceServiceImpl`",
            "> **Rule:** Constraint #9 — Spring Security proxies the interface; annotations on",
            "> impl are silently ignored at runtime.",
            "**Fix:** Move all `@PreAuthorize` annotations to `NotificationPreferenceService` interface.",
            "",
            "## Warnings (should fix)",
            "",
            "### ⚠️ WARNING-1: No `@DisallowConcurrentExecution` on Quartz Job",
            "If a background job processes preferences, it must carry `@DisallowConcurrentExecution`.",
            "Missing annotation allows concurrent runs that corrupt per-tenant queue state.",
            "",
            "### ⚠️ WARNING-2: Liquibase — NOT NULL Column without DEFAULT",
            "> `Channel_Ch VARCHAR(10) NOT NULL` on a new table is safe here (new table, no existing rows)",
            "> but `Institution_Id_In BIGINT NOT NULL` added later without a DEFAULT will cause",
            "> Liquibase startup failure on environments with existing rows. Use phased rollout.",
            "",
            "## Approvals ✅",
            "- Entity naming follows `*Tbl` convention ✅",
            "- DB column names follow `PascalCase_Underscore` ✅",
            "- Annotations on getters (not fields) ✅",
            "- LaunchDarkly flag added to `LaunchDarklyFlagEnum` ✅",
            "- Cache tier placement justified (hybrid EhCache + Redis) ✅",
            "",
            "## Summary",
            "| Category | Count |",
            "|----------|-------|",
            "| Blocking | 2 |",
            "| Warning | 2 |",
            "| Approved | 5 |",
            "",
            "**Next step:** Resolve blocking issues, re-submit for sign-off."
        ));

        // ── requirements-clarification ───────────────────────────────────────
        RESPONSES.put("requirements-clarification", lines(
            "# ❓ Requirements Clarification Report",
            "**Ticket:** PS-12345 | **Status:** Needs Clarification",
            "",
            "## Ambiguities Detected",
            "The provided requirements contain **4 ambiguous areas** that must be resolved",
            "before design can begin.",
            "",
            "## Clarifying Questions",
            "",
            "**Q1 — Scope of 'improve reporting':**",
            "Does this mean new report types, existing report performance, export formats (PDF/Excel/CSV),",
            "or the BIRT report engine upgrade? Each is a separate workstream.",
            "",
            "**Q2 — User personas:**",
            "Which roles can access the new reports? Supervisors only, or also Resources and Admins?",
            "This drives `@PreAuthorize` expressions and the ACL service calls.",
            "",
            "**Q3 — Data freshness:**",
            "Should report data be real-time (direct DB query) or near-real-time (cached)?",
            "Real-time on `staffing_tbl` with 10M+ rows requires pagination and index verification.",
            "",
            "**Q4 — Multi-institution reports:**",
            "Should a supervisor with access to multiple institutions see aggregated data,",
            "or is each report scoped to a single institution? (Multi-institution = admin-only path.)",
            "",
            "## Assumptions Made",
            "1. Feature will be gated behind a new LaunchDarkly flag (default off)",
            "2. Existing Liquibase changelog structure will be used for any new DB views",
            "3. Spring Batch will handle bulk export if export exceeds 10,000 rows",
            "4. BIRT report engine version stays at current — no upgrade in this ticket",
            "",
            "## Refined Acceptance Criteria (Draft)",
            "- [ ] AC-1: Given a Supervisor role, when navigating to Reports, then new report tab is visible",
            "- [ ] AC-2: Given an institution filter, when running the report, then only that institution's data is shown",
            "- [ ] AC-3: Given >10,000 rows, when exporting, then result is paginated / batched",
            "- [ ] AC-4: Feature toggle `PS-12345-improved-reporting` must be false by default"
        ));

        // ── story-breakdown ──────────────────────────────────────────────────
        RESPONSES.put("story-breakdown", lines(
            "# 📋 Story Breakdown — PS-12345",
            "**Epic:** Push Notification Preference Management | **Total Estimate:** 34 points",
            "",
            "## Sub-Stories",
            "",
            "| # | Story | Points | Sprint | Depends On |",
            "|---|-------|--------|--------|-----------|",
            "| 1 | DB migration: `notification_preference_tbl` | 1 | Sprint 1 | — |",
            "| 2 | Domain entity `NotificationPreferenceTbl` + DAO | 3 | Sprint 1 | #1 |",
            "| 3 | `NotificationPreferenceService` interface + impl | 5 | Sprint 1 | #2 |",
            "| 4 | `@NotificationPreferenceEvict` annotation + util | 2 | Sprint 1 | #3 |",
            "| 5 | REST endpoint `POST /api/v2/notification-preferences` | 3 | Sprint 2 | #3 |",
            "| 6 | LaunchDarkly flag + `LaunchDarklyFlagEnum` entry | 1 | Sprint 1 | — |",
            "| 7 | Unit tests: `NotificationPreferenceServiceTest` | 5 | Sprint 2 | #3 |",
            "| 8 | Integration tests: `NotificationPreferenceServiceIT` | 5 | Sprint 2 | #3 |",
            "| 9 | UI: Resource preference settings page (JSP/Tiles) | 8 | Sprint 3 | #5 |",
            "| 10| QA: Test plan execution + sign-off | 1 | Sprint 3 | #9 |",
            "",
            "## Dependency Graph",
            "```",
            "#1 Migration → #2 Entity/DAO → #3 Service → #4 Eviction",
            "                                         ↘→ #5 Controller → #9 UI",
            "#6 LD Flag (parallel, no deps)            ↘→ #7 Unit Tests",
            "                                          ↘→ #8 Integration Tests",
            "```",
            "",
            "## Sprint Allocation",
            "| Sprint | Stories | Points |",
            "|--------|---------|--------|",
            "| Sprint 1 | #1, #2, #3, #4, #6 | 12 |",
            "| Sprint 2 | #5, #7, #8 | 13 |",
            "| Sprint 3 | #9, #10 | 9 |",
            "",
            "## Notes",
            "- Story #4 (`@NotificationPreferenceEvict`) blocks all cache-related operations — do not skip",
            "- Story #6 (LD flag) should be created in LaunchDarkly dashboard before Sprint 1 ends",
            "- Story #9 (UI) can be parallelised if a second engineer picks it up alongside #7/#8"
        ));

        // ── defect-fix-designer ──────────────────────────────────────────────
        RESPONSES.put("defect-fix-designer", lines(
            "# 🛠️ Defect Fix Design — PS-821311",
            "**Defect:** Contact Manager NPE on queue processing | **Fix Type:** Code Fix",
            "",
            "## Root Cause (Confirmed)",
            "In `ContactManagerServiceImpl.processQueueEntry()` (line 847), the call to",
            "`.getContactMethodTbl().getContactMethodTypeEnum()` throws `NullPointerException`",
            "when `contactMethodTbl` is `null` — this happens after a soft-delete of a contact",
            "method that is still referenced by an in-flight queue entry.",
            "",
            "The null guard that previously existed at line 831 was removed in PS-789034.",
            "",
            "## Proposed Fix",
            "```java",
            "// ContactManagerServiceImpl.java — processQueueEntry(), line ~847",
            "// BEFORE (broken):",
            "ContactMethodTypeEnum methodType = entry.getContactMethodTbl()",
            "    .getContactMethodTypeEnum();  // NPE when contactMethodTbl is null",
            "",
            "// AFTER (fixed):",
            "if (entry.getContactMethodTbl() == null) {",
            "    log.warn(\"Queue entry {} has no contact method — skipping\",",
            "        entry.getCallQueueIdIn());",
            "    updateQueueStatus(entry, ContactManagerCallQueueStatusEnum.NO_CONTACT_METHOD);",
            "    return;",
            "}",
            "ContactMethodTypeEnum methodType = entry.getContactMethodTbl()",
            "    .getContactMethodTypeEnum();",
            "```",
            "",
            "## Additional Fix: DAO — prevent LazyInitializationException",
            "```java",
            "// ContactManagerCallQueueDao — add FETCH JOIN",
            "@Query(\"SELECT q FROM ContactManagerCallQueueTbl q \" +",
            "       \"LEFT JOIN FETCH q.contactMethodTbl \" +",
            "       \"WHERE q.institutionTbl.institutionIdIn = :institutionId \" +",
            "       \"AND q.statusEnum = :status\")",
            "List<ContactManagerCallQueueTbl> findPendingWithContactMethod(",
            "    @Param(\"institutionId\") Long institutionId,",
            "    @Param(\"status\") ContactManagerCallQueueStatusEnum status);",
            "```",
            "",
            "## Impact Analysis",
            "| Area | Impact |",
            "|------|--------|",
            "| `ContactManagerServiceImpl` | Single method change — low risk |",
            "| `ContactManagerCallQueueDao` | Query change — test with non-null + null cases |",
            "| Cache | No cache eviction needed — queue state not cached |",
            "| DB | No migration needed |",
            "",
            "## Validation Approach",
            "1. Unit test: `ContactManagerServiceImplTest.testProcessQueueEntry_nullContactMethod()`",
            "2. Integration test: `ContactManagerServiceIT` with queue entry having deleted contact method",
            "3. Manual: Create queue entry, soft-delete contact method, trigger `ContactManagerJob`",
            "",
            "## Rollback Plan",
            "Feature is behind existing `CONTACT_MANAGER_ENABLED` flag — disable flag to bypass.",
            "Git revert of the single commit if needed."
        ));

        // ── code-review ──────────────────────────────────────────────────────
        RESPONSES.put("code-review", lines(
            "# 👁️ Code Review Report",
            "**Branch:** feature/PS-12345-notification-prefs | **Verdict:** ⚠️ Request Changes",
            "",
            "## 🚫 Blocking (2)",
            "",
            "### BLOCK-1: `@Transactional` on Controller Method",
            "> `NotificationPreferenceController.savePreference()` line 67",
            "> **Rule (Constraint #8):** `@Transactional` belongs on service impl mutations only.",
            "> On a controller it creates a transaction that spans the HTTP response serialisation,",
            "> holding a DB connection unnecessarily.",
            "**Fix:** Remove `@Transactional` from controller. It is already present on the service impl.",
            "",
            "### BLOCK-2: No ACL Check Before Data Access",
            "> `NotificationPreferenceServiceImpl.getPreferences()` calls DAO directly without",
            "> calling `CommonACLService.validateResourceAccess(resourceId, institutionId)`.",
            "> **Rule (service-acl.md):** `@PreAuthorize` checks roles only; ACL validates org scope.",
            "**Fix:** Add `commonACLService.validateResourceAccess(resourceId, institutionId)` as first call.",
            "",
            "## ⚠️ Warnings (3)",
            "",
            "### WARN-1: Star Import",
            "> `import com.kronos.telestaff.domain.*;` in `NotificationPreferenceServiceImpl`",
            "> Violates Checkstyle rule. Replace with explicit imports.",
            "",
            "### WARN-2: Lazy-Loaded Collection in Cached Object",
            "> `NotificationPreferenceTbl.getResourceTbl()` is `@ManyToOne(fetch=LAZY)` but the",
            "> entity is cached in Redis. Accessing `resourceTbl` after deserialization will throw",
            "> `LazyInitializationException`. Use `@ManyToOne(fetch=EAGER)` or a projection DTO for caching.",
            "",
            "### WARN-3: Missing `default` in Switch Statement",
            "> `NotificationPreferenceServiceImpl.mapChannel()` switch on `channelCh` has no `default`.",
            "> Violates Checkstyle. Add `default: throw new IllegalArgumentException(...)` or log and skip.",
            "",
            "## ✅ Approved",
            "- `*Tbl` entity naming convention followed ✅",
            "- `@PreAuthorize` on service interface, not impl ✅",
            "- Liquibase migration: nullable column, no NOT NULL without DEFAULT ✅",
            "- LD flag check wraps feature entry point ✅",
            "- `@NotificationPreferenceEvict` used (not manual cache ops) ✅"
        ));

        // ── root-cause-analysis ──────────────────────────────────────────────
        RESPONSES.put("root-cause-analysis", lines(
            "# 🔎 Root Cause Analysis",
            "**Problem:** `LazyInitializationException` in production — ResourceCacheService",
            "",
            "## Problem Statement",
            "Since release 2024.4, approximately 12% of requests to `/api/v2/roster`",
            "fail with `org.hibernate.LazyInitializationException: could not initialize proxy`.",
            "Impact: Roster load failures for ~340 users/day across 8 institutions.",
            "",
            "## 5-Why Analysis",
            "",
            "**Why 1:** Why does the roster endpoint throw `LazyInitializationException`?",
            "→ `ResourceMasterTbl.getUnitTbl()` is accessed outside an active Hibernate session.",
            "",
            "**Why 2:** Why is `unitTbl` accessed outside a session?",
            "→ The `ResourceMasterTbl` object is retrieved from the Redis cache (deserialized).",
            "   Deserialized objects have no attached session — Hibernate proxies cannot be initialised.",
            "",
            "**Why 3:** Why was a Hibernate proxy stored in Redis?",
            "→ `ResourceCacheServiceImpl.cacheResource()` stores the entity directly rather than a",
            "   DTO projection. `unitTbl` was still an uninitialised proxy at caching time.",
            "",
            "**Why 4:** Why was `unitTbl` uninitialised when the entity was cached?",
            "→ The caching call happens after the transaction commits in `ResourceServiceImpl.saveResource()`.",
            "   Outside the transaction, lazy association `unitTbl` is never loaded.",
            "",
            "**Why 5:** Why did this start in 2024.4 and not before?",
            "→ `ResourceServiceImpl.saveResource()` was refactored in PS-789041 to cache eagerly",
            "   post-commit (for performance). Prior code cached inside the transaction. Root cause: **regression**.",
            "",
            "## Contributing Factors",
            "- No FST serialization guard checking for uninitialised proxies before Redis put",
            "- Missing `@FetchType.EAGER` override on `unitTbl` for cached entities",
            "- No integration test covering cache-then-deserialize scenario for `ResourceMasterTbl`",
            "",
            "## Fix Plan",
            "1. **Immediate:** Cache a DTO projection (not the entity) in `ResourceCacheServiceImpl`",
            "2. **Short-term:** Add `@FetchType.EAGER` to `unitTbl` or a `JOIN FETCH` in the cache-fill query",
            "3. **Prevention:** Add `AbstractCacheIT` test base that validates no Hibernate proxy in cached objects",
            "",
            "## Prevention Recommendations",
            "- Review all `@Cacheable` methods that return `*Tbl` entities — audit for lazy associations",
            "- Add caching-review checklist item: _No Hibernate proxies or lazy collections in Redis caches_"
        ));

        // ── junit-test-generator ─────────────────────────────────────────────
        RESPONSES.put("junit-test-generator", lines(
            "# 🧪 JUnit Tests — NotificationPreferenceServiceImpl",
            "**Class:** `com.kronos.telestaff.service.impl.NotificationPreferenceServiceImpl`",
            "**Test Type:** Unit Test (JUnit 5 + Mockito)",
            "",
            "```java",
            "package com.kronos.telestaff.service.impl;",
            "",
            "import com.kronos.telestaff.dao.NotificationPreferenceDao;",
            "import com.kronos.telestaff.domain.NotificationPreferenceTbl;",
            "import com.kronos.telestaff.dto.NotificationPreferenceDto;",
            "import com.kronos.telestaff.service.acl.CommonACLService;",
            "import com.kronos.common.service.featureFlag.FeatureFlagService;",
            "import com.kronos.common.util.launchdarkly.LaunchDarklyFlagEnum;",
            "import org.junit.jupiter.api.BeforeEach;",
            "import org.junit.jupiter.api.Test;",
            "import org.junit.jupiter.api.extension.ExtendWith;",
            "import org.mockito.InjectMocks;",
            "import org.mockito.Mock;",
            "import org.mockito.junit.jupiter.MockitoExtension;",
            "",
            "import java.util.Optional;",
            "",
            "import static org.assertj.core.api.Assertions.*;",
            "import static org.mockito.BDDMockito.*;",
            "",
            "@ExtendWith(MockitoExtension.class)",
            "class NotificationPreferenceServiceImplTest {",
            "",
            "    @Mock NotificationPreferenceDao notificationPreferenceDao;",
            "    @Mock CommonACLService           commonACLService;",
            "    @Mock FeatureFlagService          featureFlagService;",
            "",
            "    @InjectMocks NotificationPreferenceServiceImpl service;",
            "",
            "    @BeforeEach",
            "    void setUp() {",
            "        given(featureFlagService.isFeatureEnabled(any(LaunchDarklyFlagEnum.class)))",
            "            .willReturn(true);",
            "    }",
            "",
            "    @Test",
            "    void getPreferences_returnsDto_whenResourceExists() {",
            "        var entity = buildPreference(1L, 100L, \"EMAIL\", \"Y\");",
            "        given(notificationPreferenceDao.findAllByResource(1L, 100L))",
            "            .willReturn(List.of(entity));",
            "",
            "        NotificationPreferenceDto result = service.getPreferences(1L);",
            "",
            "        assertThat(result.getResourceId()).isEqualTo(1L);",
            "        assertThat(result.getChannels()).containsKey(\"EMAIL\");",
            "    }",
            "",
            "    @Test",
            "    void getPreferences_throwsAccessDenied_whenACLFails() {",
            "        willThrow(new AccessDeniedException(\"No access\"))",
            "            .given(commonACLService).validateResourceAccess(99L, 100L);",
            "",
            "        assertThatThrownBy(() -> service.getPreferences(99L))",
            "            .isInstanceOf(AccessDeniedException.class);",
            "    }",
            "",
            "    @Test",
            "    void savePreference_callsUpsert_andEvictsCache() {",
            "        var dto = new NotificationPreferenceDto(1L, 100L, \"PUSH\", true);",
            "        service.savePreference(dto);",
            "        then(notificationPreferenceDao).should().upsert(any());",
            "    }",
            "",
            "    @Test",
            "    void savePreference_noOp_whenFeatureFlagDisabled() {",
            "        given(featureFlagService.isFeatureEnabled(any())).willReturn(false);",
            "        service.savePreference(new NotificationPreferenceDto());",
            "        then(notificationPreferenceDao).shouldHaveNoInteractions();",
            "    }",
            "",
            "    private NotificationPreferenceTbl buildPreference(",
            "            Long resourceId, Long institutionId, String channel, String enabled) {",
            "        // ... builder / setter construction",
            "        return new NotificationPreferenceTbl();",
            "    }",
            "}",
            "```"
        ));

        // ── test-plan-generator ──────────────────────────────────────────────
        RESPONSES.put("test-plan-generator", lines(
            "# 📝 Test Plan — Notification Preference Management (PS-12345)",
            "**Scope:** Full Coverage | **Test Levels:** Unit, Integration, Manual E2E",
            "",
            "## Test Scenarios",
            "",
            "### TS-01: Retrieve preferences for a resource",
            "| # | Step | Expected |",
            "|---|------|---------|",
            "| 1 | Call `GET /api/v2/notification-preferences?resourceId=1001` as Supervisor | 200 OK with preference list |",
            "| 2 | Call same endpoint as a Resource for own ID | 200 OK |",
            "| 3 | Call as Resource for another Resource's ID | 403 Forbidden |",
            "",
            "### TS-02: Save / update a preference",
            "| # | Step | Expected |",
            "|---|------|---------|",
            "| 1 | POST `{resourceId:1001, channel:'PUSH', enabled:true}` | 200 OK, preference persisted |",
            "| 2 | POST same again with `enabled:false` | 200 OK, preference updated (upsert) |",
            "| 3 | POST with invalid channel `'FAX'` | 400 Bad Request |",
            "",
            "### TS-03: Feature flag gating",
            "| # | Step | Expected |",
            "|---|------|---------|",
            "| 1 | Disable LD flag `PS-12345-push-notification-prefs` | API returns 404 or feature-not-enabled response |",
            "| 2 | Re-enable flag | API resumes normal operation |",
            "",
            "### TS-04: Multi-institution isolation",
            "| # | Step | Expected |",
            "|---|------|---------|",
            "| 1 | Create preference for Institution A | Only visible under Institution A |",
            "| 2 | Fetch preferences under Institution B (same tenant) | Institution A preference NOT returned |",
            "",
            "### TS-05: Cache behaviour",
            "| # | Step | Expected |",
            "|---|------|---------|",
            "| 1 | Fetch preferences twice in < 30 min | Second call served from Redis |",
            "| 2 | Save preference, then fetch | Cache evicted — fresh DB read returned |",
            "",
            "### TS-06: Contact Manager respects opt-out",
            "| # | Step | Expected |",
            "|---|------|---------|",
            "| 1 | Set PUSH=disabled for Resource 1001 | ContactManagerJob skips push for 1001 |",
            "| 2 | Re-enable PUSH | ContactManagerJob resumes push for 1001 |",
            "",
            "## Acceptance Criteria Traceability",
            "| AC | Test Scenario |",
            "|----|--------------|",
            "| AC-1: Supervisor sees preference UI | TS-01 #1 |",
            "| AC-2: Institution filter applied | TS-04 |",
            "| AC-3: Opt-out respected by Contact Manager | TS-06 |",
            "| AC-4: LD flag default-off | TS-03 #1 |"
        ));

        // ── risk-assessment ──────────────────────────────────────────────────
        RESPONSES.put("risk-assessment", lines(
            "# ⚠️ Risk Assessment — PS-12345 Notification Preference Management",
            "**Change Type:** New Feature | **Overall Risk Score:** Medium (6.2/10)",
            "",
            "## Risk Register",
            "",
            "| ID | Risk | Likelihood | Impact | Score | Mitigation |",
            "|----|------|-----------|--------|-------|-----------|",
            "| R-1 | Cross-institution data leak if institution filter missing on DAO | Medium | Critical | 8.5 | Design review gate; ACL service call mandatory |",
            "| R-2 | Cache stale after preference update (missing eviction) | Medium | High | 7.0 | `@NotificationPreferenceEvict` annotation enforced in code review |",
            "| R-3 | LazyInitializationException if entity cached with Hibernate proxy | Low | High | 5.5 | Cache DTO projection, not entity; FST serialization test |",
            "| R-4 | Contact Manager regression if preference read fails silently | Low | High | 5.0 | Null-safe preference lookup; default to opted-in |",
            "| R-5 | LD flag accidentally enabled in prod before feature is complete | Low | Medium | 4.0 | Default-off flag; separate LD environment targets |",
            "| R-6 | DB migration failure on non-empty environments | Low | Medium | 3.5 | Nullable columns; tested on staging with prod-representative data |",
            "",
            "## Top Risk: R-1 — Cross-Institution Data Leak",
            "**Scenario:** `NotificationPreferenceDao.findAllByResource(resourceId)` without",
            "`institutionId` filter returns preferences from ALL institutions for that resource.",
            "A Supervisor in Institution B could see preferences configured in Institution A.",
            "",
            "**Controls:**",
            "1. Design review checklist item: ACL + institution filter on all queries",
            "2. `BaseMultiTenantIT` integration test: create pref in Institution A, verify invisible to Institution B",
            "3. `CommonACLService.validateResourceAccess()` call at service entry point",
            "",
            "## Contingency Plan",
            "- **R-1 triggered in prod:** Disable LD flag immediately; query rollback via Liquibase `rollback` tag",
            "- **R-3 triggered:** Flush Redis cache for `NOTIFICATION_PREFERENCE_CACHE` via JMX MBean",
            "- **R-4 triggered:** ContactManager falls back to all-channels-enabled default; no customer impact"
        ));

        // ── environment-provisioning ─────────────────────────────────────────
        RESPONSES.put("environment-provisioning", lines(
            "# ☁️ GCP Environment Provisioning Runbook",
            "**Environment:** dev-ps-12345 | **Type:** Dev | **Region:** us-central1",
            "",
            "## Pre-requisites",
            "- [ ] GCP project `ukg-telestaff-dev` exists and billing enabled",
            "- [ ] `gcloud` CLI authenticated with `roles/editor` minimum",
            "- [ ] Helm 3.x installed; `kubectl` context pointing to target cluster",
            "- [ ] Secrets provisioned in GCP Secret Manager (DB password, JWT secret, SAML cert)",
            "",
            "## Step 1 — Cloud SQL (PostgreSQL 17)",
            "```bash",
            "gcloud sql instances create telestaff-dev-ps12345 \\",
            "  --database-version=POSTGRES_17 \\",
            "  --tier=db-f1-micro \\",
            "  --region=us-central1 \\",
            "  --storage-type=SSD \\",
            "  --storage-size=20GB",
            "",
            "gcloud sql databases create telestaff --instance=telestaff-dev-ps12345",
            "```",
            "",
            "## Step 2 — Memorystore Redis",
            "```bash",
            "gcloud redis instances create telestaff-dev-ps12345 \\",
            "  --size=1 \\",
            "  --region=us-central1 \\",
            "  --redis-version=redis_7_0",
            "```",
            "",
            "## Step 3 — GKE Deployment (Helm)",
            "```bash",
            "# tsc repo — helm chart: tsc-telestaff",
            "helm upgrade --install telestaff-dev-ps12345 ./charts/tsc-telestaff \\",
            "  --namespace dev-ps12345 \\",
            "  --set image.tag=feature-ps-12345-latest \\",
            "  --set db.host=<cloud-sql-private-ip> \\",
            "  --set redis.host=<memorystore-ip> \\",
            "  --values ./envs/dev/values.yaml",
            "```",
            "",
            "## Step 4 — Post-Deploy Checks",
            "- [ ] `telestaff-web` pod Running: `kubectl get pods -n dev-ps12345`",
            "- [ ] Liquibase migrations applied: check `databasechangelog` table",
            "- [ ] Health endpoint green: `curl http://<lb-ip>/telestaff-web/actuator/health`",
            "- [ ] `telestaff.tenant2` hosts entry added (or DNS record created)",
            "- [ ] Redis connectivity verified: `redis-cli -h <ip> PING`",
            "",
            "## Step 5 — Tenant Setup",
            "```sql",
            "-- Run after migration on new Cloud SQL instance",
            "INSERT INTO edap_tenant (tenant_id, name) VALUES ('tenant2', 'Demo Tenant');",
            "SET search_path TO tenant2;",
            "INSERT INTO institution_tbl (institution_name_ch) VALUES ('Demo Institution');",
            "```"
        ));

        // ── release-deployment ───────────────────────────────────────────────
        RESPONSES.put("release-deployment", lines(
            "# 🚀 Deployment Plan — Release 2025.1.0",
            "**Deployment Type:** Rolling Deploy | **Window:** Sat 2025-01-18 02:00–06:00 UTC",
            "",
            "## Pre-Deployment Checklist",
            "- [ ] All stories in release merged and `mvn clean install` green on `main`",
            "- [ ] Liquibase changelog reviewed by DBA — no blocking DDL (`ALTER TABLE` on large tables)",
            "- [ ] LD flags for new features verified default-off in production",
            "- [ ] Redis flush scheduled for caches affected by entity changes",
            "- [ ] Rollback artifacts tagged: `release/2025.0.3` Docker images accessible",
            "- [ ] Go/No-Go call with QA lead and on-call SRE confirmed",
            "",
            "## Deployment Steps",
            "1. **02:00** — Stop Quartz scheduler on all nodes (`QuartzJobManager.pauseAll()`)",
            "2. **02:05** — Run Liquibase migration (`mvn -pl telestaff-web exec:java@migrate-telestaff`)",
            "3. **02:15** — Rolling restart Node 1 (30% traffic) — monitor error rate < 0.5%",
            "4. **02:35** — Rolling restart Node 2 — monitor",
            "5. **02:55** — Rolling restart Node 3 — all nodes on 2025.1.0",
            "6. **03:00** — Resume Quartz scheduler",
            "7. **03:05** — Smoke test: login, roster load, schedule view, contact manager status",
            "8. **03:30** — Go/No-Go decision: proceed to full or rollback",
            "",
            "## Go / No-Go Criteria",
            "| Metric | Threshold | Action if Breached |",
            "|--------|-----------|-------------------|",
            "| Error rate (5xx) | < 0.5% | STOP — rollback immediately |",
            "| P99 response time | < 3,000 ms | WARN — continue with monitoring |",
            "| Active sessions after restart | > 80% pre-deploy baseline | OK |",
            "| Liquibase migration status | `EXECUTED` for all changeSets | STOP if any FAILED |",
            "",
            "## Rollback Procedure",
            "1. Helm rollback: `helm rollback telestaff-prod $(helm history telestaff-prod --max 2 | tail -1 | awk '{print $1}')`",
            "2. If DB migration applied: run Liquibase rollback for 2025.1.0 changeSets",
            "3. Re-enable LD flags that were toggled off",
            "4. Post-incident review within 24 hours"
        ));

        // ── release-notes ────────────────────────────────────────────────────
        RESPONSES.put("release-notes", lines(
            "# 📄 Release Notes — TeleStaff 2025.1.0",
            "**Release Date:** January 18, 2025 | **Audience:** All",
            "",
            "## New Features",
            "",
            "### 🔔 Notification Preference Management (PS-12345)",
            "Resources can now manage their own notification preferences (push, email, SMS)",
            "directly from the My Profile page — no admin request required.",
            "Supervisors can manage preferences on behalf of their direct reports.",
            "",
            "### 📊 Enhanced Roster Reporting (PS-12289)",
            "The Roster Report now supports multi-institution aggregation for Admin users,",
            "with export to Excel (up to 50,000 rows via Spring Batch).",
            "New date-range presets: Last 7 days, Last 30 days, Custom range.",
            "",
            "### ⚡ Contact Manager Performance (PS-12401)",
            "Queue processing throughput improved by 40% through optimised DAO queries",
            "(`LEFT JOIN FETCH` on contact method) and Redis-backed queue state.",
            "",
            "## Bug Fixes",
            "",
            "| Ticket | Summary |",
            "|--------|---------|",
            "| PS-821311 | Contact Manager NPE on null contact method after soft-delete |",
            "| PS-821298 | LazyInitializationException in ResourceCacheService on roster load |",
            "| PS-821177 | Quartz job stuck in JOB_TRIGGERED after exception swallowed |",
            "| PS-820944 | Cross-institution data visible in focus filter when institution FK missing |",
            "",
            "## Security Fixes",
            "- PS-821200: Added missing `@PreAuthorize` on `StaffingReportService.exportReport()`",
            "",
            "## Deprecations",
            "- `ContactManagerServiceImpl.processLegacyQueue()` — will be removed in 2025.2.0.",
            "  Use `processQueueEntry()` instead.",
            "",
            "## Upgrade Notes",
            "- Liquibase migration adds `notification_preference_tbl` — runs automatically on startup",
            "- Redis cache key format changed for `RESOURCE_CACHE` — flush Redis after deployment",
            "- LD flag `PS-12345-push-notification-prefs` must be enabled to activate preference UI"
        ));

        // ── sprint-readiness ─────────────────────────────────────────────────
        RESPONSES.put("sprint-readiness", lines(
            "# 📊 Sprint Readiness Report — Sprint 2025-01",
            "**Capacity:** 40 points | **Committed:** 38 points | **Readiness Score: 76/100**",
            "",
            "## Story Status",
            "",
            "| Ticket | Story | Points | Status | Risk |",
            "|--------|-------|--------|--------|------|",
            "| PS-12345 | Notification Preference Entity + DAO | 3 | ✅ Ready | Low |",
            "| PS-12346 | Notification Preference Service | 5 | ✅ Ready | Low |",
            "| PS-12347 | REST Endpoint `/api/v2/notification-preferences` | 3 | ⚠️ At Risk | Medium |",
            "| PS-12348 | LD Flag + LaunchDarklyFlagEnum | 1 | ✅ Ready | Low |",
            "| PS-12289 | Roster Report Multi-Institution | 8 | ⚠️ At Risk | High |",
            "| PS-12401 | Contact Manager DAO Query Optimisation | 5 | ✅ Ready | Low |",
            "| PS-821311 | Contact Manager NPE Fix | 2 | ✅ Ready | Low |",
            "| PS-12350 | Unit Tests — Notification Prefs | 5 | 🔴 Not Ready | High |",
            "| PS-12351 | Integration Tests | 5 | 🔴 Not Ready | High |",
            "",
            "## Risks",
            "",
            "### ⚠️ PS-12347 — REST Endpoint At Risk",
            "Design review (PS-12345) not yet signed off — blocking issue BLOCK-2 (missing ACL check)",
            "must be resolved before implementation can start. **Blocker: Design review.**",
            "",
            "### ⚠️ PS-12289 — Roster Report High Risk",
            "DB migration requires DBA review of new index on `roster_assignment_tbl` (18M rows).",
            "Index must use `CONCURRENTLY` — review not scheduled yet.",
            "**Blocker: DBA review + maintenance window.**",
            "",
            "### 🔴 PS-12350/12351 — Tests Not Ready",
            "Test stubs depend on PS-12346 (service) being merged first.",
            "If Sprint 1 service story slips, tests will not be ready by sprint end.",
            "",
            "## Recommendations",
            "1. Schedule design review sign-off for PS-12345 by Day 2 of sprint",
            "2. DBA review for PS-12289 index needs to be booked in next 24 hours",
            "3. Consider deferring PS-12350/12351 to Sprint 2 and replacing with PS-821298 (bug fix, 3 pts)",
            "4. 38 committed points vs 40 capacity — 2-point buffer is thin; monitor daily"
        ));

        // ── create-open-prs ──────────────────────────────────────────────────
        RESPONSES.put("create-open-prs", lines(
            "# 🔀 Pull Request Package — PS-12345",
            "**Branch:** `feature/PS-12345-notification-prefs` → `main`",
            "**Repos:** workforce-telestaff, kronos-common | **Type:** Feature",
            "",
            "---",
            "",
            "## 1. workforce-telestaff",
            "",
            "### Title",
            "```",
            "[PS-12345] Add notification preference management for resources",
            "```",
            "",
            "### Description",
            "```markdown",
            "## Summary",
            "- Adds `NotificationPreferenceTbl` entity and DAO for per-resource, per-channel",
            "  (PUSH / EMAIL / SMS) opt-in/opt-out preferences",
            "- New `NotificationPreferenceService` with ACL-gated read/write methods",
            "- REST endpoint `POST /api/v2/notification-preferences` (Pattern B — `APIResponse<T>`)",
            "- `ContactManagerServiceImpl` now respects opt-out before dispatching",
            "- Liquibase migration: `20250101_notification_prefs.xml` (nullable columns, safe)",
            "- Feature gated behind LD flag `PS-12345-push-notification-prefs` (default off)",
            "",
            "## Test Plan",
            "- [ ] `NotificationPreferenceServiceImplTest` — 6 unit tests, all green",
            "- [ ] `NotificationPreferenceServiceIT` — integration tests with DB rollback",
            "- [ ] `BaseMultiTenantIT` — verified no cross-institution data leak",
            "- [ ] Manual: enable LD flag on dev, set opt-out, trigger ContactManagerJob,",
            "       confirm resource skipped in contact queue",
            "",
            "## Checklist",
            "- [x] LaunchDarkly flag wraps all entry points",
            "- [x] `@PreAuthorize` on service interface (not impl)",
            "- [x] `@Transactional` on service impl mutations only",
            "- [x] Institution filter on all DAO queries (no cross-institution leak)",
            "- [x] `@NotificationPreferenceEvict` annotation on all write paths",
            "- [x] Liquibase: nullable columns, no blocking DDL",
            "- [x] No Hibernate lazy proxies stored in Redis",
            "",
            "🤖 Generated with [Telestaff SDLC Agents Portal](http://localhost:9090)",
            "```",
            "",
            "### gh CLI Command",
            "```bash",
            "cd /path/to/workforce-telestaff",
            "gh pr create \\",
            "  --title \"[PS-12345] Add notification preference management for resources\" \\",
            "  --body \"$(cat <<'EOF'",
            "## Summary",
            "...(see description above)...",
            "EOF",
            ")\" \\",
            "  --base main \\",
            "  --head feature/PS-12345-notification-prefs",
            "```",
            "",
            "---",
            "",
            "## 2. kronos-common",
            "",
            "### Title",
            "```",
            "[PS-12345] Add PS_12345_PUSH_NOTIFICATION_PREFS to LaunchDarklyFlagEnum",
            "```",
            "",
            "### Description",
            "```markdown",
            "## Summary",
            "- Adds `PS_12345_PUSH_NOTIFICATION_PREFS(\"PS-12345-push-notification-prefs\")`",
            "  to `LaunchDarklyFlagEnum` in `telestaff-commons`",
            "- Default: `false` (off) — no customer impact on deploy",
            "",
            "## Checklist",
            "- [x] Flag key matches LaunchDarkly dashboard entry exactly",
            "- [x] Default is `false` — safe to deploy before LD flag is created",
            "- [x] No other code changes in this PR",
            "",
            "🤖 Generated with [Telestaff SDLC Agents Portal](http://localhost:9090)",
            "```",
            "",
            "### gh CLI Command",
            "```bash",
            "cd /path/to/kronos-common",
            "gh pr create \\",
            "  --title \"[PS-12345] Add PS_12345_PUSH_NOTIFICATION_PREFS to LaunchDarklyFlagEnum\" \\",
            "  --body \"$(cat <<'EOF'",
            "## Summary",
            "...(see description above)...",
            "EOF",
            ")\" \\",
            "  --base main \\",
            "  --head feature/PS-12345-notification-prefs",
            "```",
            "",
            "---",
            "",
            "## Cross-Repo Merge Order",
            "```",
            "1. kronos-common PR  →  merge first (LaunchDarklyFlagEnum change)",
            "2. workforce-telestaff PR  →  merge after kronos-common is published to Nexus",
            "```",
            "",
            "## Post-Merge Checklist",
            "- [ ] kronos-common version bumped and published to Nexus",
            "- [ ] workforce-telestaff `pom.xml` updated to new kronos-common version",
            "- [ ] LD flag `PS-12345-push-notification-prefs` created in LaunchDarkly dashboard (default off)",
            "- [ ] Redis cache flush scheduled for `NOTIFICATION_PREFERENCE_CACHE` on deployment",
            "- [ ] Release notes entry added for 2025.1.0"
        ));

        // ── production-incident ──────────────────────────────────────────────
        RESPONSES.put("production-incident", lines(
            "# 🚨 Production Incident Report — INC-20241114-001",
            "**Severity:** P1 — High | **Duration:** 47 min | **Status:** Resolved",
            "",
            "## Executive Summary",
            "On 2024-11-14 03:17 UTC, `telestaff-web` began returning 502 errors for ~18% of requests.",
            "Root cause: Redis Memorystore instance hit memory limit, causing `maxmemory-policy allkeys-lru`",
            "to evict Spring Session keys, logging out active users.",
            "",
            "## Timeline",
            "| Time (UTC) | Event |",
            "|-----------|-------|",
            "| 03:17 | PagerDuty alert: error rate > 5% on `telestaff-web` |",
            "| 03:19 | On-call SRE acknowledges; begins investigation |",
            "| 03:24 | Redis memory usage confirmed at 99.8% (`INFO memory`) |",
            "| 03:31 | Identified Spring Session key eviction as cause of 401 cascade |",
            "| 03:38 | GCP Console: Redis instance scaled from 1 GB to 4 GB |",
            "| 03:44 | Error rate drops to 0.3% — users prompted to re-login |",
            "| 04:04 | All metrics normal; incident resolved |",
            "",
            "## Root Cause",
            "Redis `NOTIFICATION_PREFERENCE_CACHE` was incorrectly configured with no TTL,",
            "causing unbounded growth. A batch job (PS-12401 ContactManager optimisation) added",
            "~250 MB of cache entries overnight without eviction.",
            "",
            "## Impact",
            "- ~1,400 active sessions evicted (users logged out mid-shift)",
            "- 47 minutes of degraded service (18% error rate at peak)",
            "- 3 institutions reported missed contact attempts during the window",
            "",
            "## Corrective Actions",
            "| Action | Owner | Due Date |",
            "|--------|-------|---------|",
            "| Add TTL to `NOTIFICATION_PREFERENCE_CACHE` in `RedisConfigCreator` | Dev Team | 2024-11-15 |",
            "| Add Redis memory alert at 70% threshold in GCP Monitoring | SRE | 2024-11-15 |",
            "| Audit all Redis caches without TTL via `RedisConfigCreator` review | Tech Lead | 2024-11-21 |",
            "| Add load test for Redis memory under batch job execution | QA | 2024-11-28 |",
            "",
            "## Prevention",
            "- Enforce TTL on ALL Redis caches via a CI gate in `RedisConfigCreator` (new lint rule)",
            "- Capacity planning: Redis instance size should be reviewed after each major feature"
        ));
    }

    /**
     * Returns the canned demo response for the given agent, with input values
     * spliced in where available (e.g. Jira ID, feature name).
     */
    public String getResponse(String agentId, Map<String, String> inputs) {
        String base = RESPONSES.getOrDefault(agentId, DEFAULT_RESPONSE);

        // Personalise with user inputs where present
        String jiraId = inputs.getOrDefault("jiraId",
                         inputs.getOrDefault("incidentId",
                         inputs.getOrDefault("flagKey", "PS-12345")));
        String feature = inputs.getOrDefault("requirements",
                          inputs.getOrDefault("featureDescription",
                          inputs.getOrDefault("epicDescription", "")));

        base = base.replace("PS-12345", jiraId.isBlank() ? "PS-12345" : jiraId);
        if (!feature.isBlank() && feature.length() < 60) {
            // Only splice short descriptions to avoid garbling the response
            base = base.replaceFirst("Push Notification Preference Management", feature);
        }
        return base;
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private static String lines(String... lines) {
        return String.join("\n", lines);
    }

    // ── default fallback ─────────────────────────────────────────────────────

    private static final String DEFAULT_RESPONSE = lines(
        "# ✅ Analysis Complete",
        "",
        "## Summary",
        "The agent has completed its analysis of the provided inputs.",
        "",
        "## Findings",
        "- **Classification:** Feature implementation required",
        "- **Affected modules:** `telestaff-services`, `telestaff-web`, `telestaff-domain`",
        "- **Estimated effort:** 8–13 story points across 2 sprints",
        "- **Risk level:** Medium",
        "",
        "## Recommended Next Steps",
        "1. Review the findings above with your team",
        "2. Create sub-stories in Jira with the breakdown provided",
        "3. Schedule design review before implementation begins",
        "4. Ensure LaunchDarkly flag is created before coding starts",
        "",
        "## Key Constraints Verified",
        "- ✅ Feature flag gate planned (`LaunchDarklyFlagEnum` entry required)",
        "- ✅ Multi-tenancy: institution filter confirmed on all queries",
        "- ✅ Cache eviction: `@XxxEvict` annotation strategy defined",
        "- ✅ `@PreAuthorize` placement: on service interface methods",
        "- ✅ `@Transactional` placement: on service impl mutations only"
    );
}
